### ISSUE TITLE
Plugin Tagregator

### ISSUE THREAD

**Issue by everaldomatias** [brasadesign/dia-do-graffiti-theme#11]
Instalar esse plugin Tagregator https://wordpress.org/plugins/tagregator/ e ver a possibilidade de adicionar na home. Precisa entender se conseguimos colocar o shortcode direto no PHP com do_shortcode(). E o mais importante, limitar a quantidade que é exibida na home.

![print](https://cloud.githubusercontent.com/assets/1918474/6672444/590f0bee-cbeb-11e4-85c8-c2421cc6f61a.png)

E nessa faixa verde, colocar o link para uma página com todos os itens do Tagregator.

**Comment by matheusgimenez** [comment]
Não tem como limitar esse plugin.. Tem alguma ideia de como podemos fazer isso?

**Comment by matheusgimenez** [comment]
E pra melhorar, ele não ta funcionando com do_shortcode :(

**Comment by everaldomatias** [comment]
Matheus vamos tirar isso da home então. Por hora deixe apenas o botão e cólica o shortcode em uma page mesmo.

**Comment by matheusgimenez** [comment]
Consegui já ajeitar eve.. esqueci de marcar aqui, malz :(

Fiz o seguinte, na home usei um height fixo e overflow:hidden pra aparecer só uma parte dos tweets. Ficou como no layout mesmo :)

**Comment by everaldomatias** [comment]
o/

**Comment by everaldomatias** [comment]
@matheusgimenez tenta ver no que erramos nessa config por favor? Será que é porque é multisite?

**Comment by matheusgimenez** [comment]
@everaldomatias testei no multisite no wp.codeispoetry.info, funcionou de boa lá

**Comment by everaldomatias** [comment]
Tenta gerar novamente os key's, veja se os que você tem não funcionam.

**Comment by matheusgimenez** [comment]
feito no ultimo commit

**Comment by everaldomatias** [comment]
SENSACIONAL
