### ISSUE TITLE
Reveal Modal Agenda

### ISSUE THREAD

**Issue by everaldomatias** [brasadesign/dia-do-graffiti-theme#13]
@matheusgimenez nesse primeiro momento do projeto, vamos colocar os posts da agenda como modal com nosso plugin.

Vamos solucionar isso sem single nesse momento.

**Comment by matheusgimenez** [comment]
Eve, de qualquer forma temos que pensar como vai ser o single disso no modal né?

**Comment by everaldomatias** [comment]
Sim. Deixa comigo que crio um layout. Mas vai ser simples ao extremo.

Volto aqui quando estiver pronto.

Valew.

**Comment by everaldomatias** [comment]
@matheusgimenez segue o layout (o PSD está no Drive)

![dia-do-graffiti -layout-home-com-reveal-v1](https://cloud.githubusercontent.com/assets/1918474/6733355/89389a46-ce30-11e4-93b5-0f205685f79c.jpg)

**Comment by everaldomatias** [comment]
As cores aqui pega daquele mesmo jeito do options @matheusgimenez
