### ISSUE TITLE
Área de Curadores

### ISSUE THREAD

**Issue by everaldomatias** [brasadesign/dia-do-graffiti-theme#17]
@matheusgimenez aqui vamos usar o CPT de Equipe que acabamos de aplicar na Brasa, mas ele deve chamar Curadoria. Não precisamos de single, apenas do archive como está no layout abaixo.

Os campos aqui precisam ser:
- Nome (title);
- Descrição (content);
- Foto (feature image);
- Link (com ACF).

![dia-do-graffiti -layout-curadoria](https://cloud.githubusercontent.com/assets/1918474/6771073/d2dc335e-d0b2-11e4-869f-52e6cb23afb1.jpg)

**Comment by matheusgimenez** [comment]
feito no ultimo commit

**Comment by everaldomatias** [comment]
Ficou animal Matheus... apenas um detalhe. Muda tudo que está como Equipe para Curadoria, tipo o nome do CPT, slug...
