### ISSUE TITLE
Single (Posts)

### ISSUE THREAD

**Issue by everaldomatias** [brasadesign/dia-do-graffiti-theme#18]
@matheusgimenez segue o layout da single. Usa como base o layout da home e adiciona a sidebar.

![dia-do-graffiti -layout-single](https://cloud.githubusercontent.com/assets/1918474/6780346/fff8f10c-d142-11e4-9c48-1281cba5d3f9.jpg)

**Comment by matheusgimenez** [comment]
feito no ultimo commit

**Comment by everaldomatias** [comment]
Sobe no BrasaWP por favor..

**Comment by matheusgimenez** [comment]
ops.. esqueci do background.. corrigido e enviado no ultimo commmit

**Comment by everaldomatias** [comment]
Boa.
