### ISSUE TITLE
Publicação no WP.org

### ISSUE THREAD

**Issue by matheusgimenez** [brasadesign/dia-do-graffiti-theme#34]

**Comment by everaldomatias** [comment]
Publicou?

**Comment by matheusgimenez** [comment]
Não, hehe, fui criar um milestone acabei criando uma issue e pelo jeito não rola deletar.

Mas segue um milestone com uma lista completa fruto de uma analise minha no tema:

https://github.com/brasadesign/dia-do-graffiti-theme/milestone/9
