### ISSUE TITLE
Opções de Cores

### ISSUE THREAD

**Issue by everaldomatias** [brasadesign/dia-do-graffiti-theme#4]
Adicionar dois campos de cores ao Options (aba Geral).
- Background das barras (o que no layout está com cinza escuro liso);
- Cor principal (fontes e demais destaques que estão em verde no layout).

**Comment by matheusgimenez** [comment]
Vish mano.. enrolado esse de setar todas as cores hein?

**Comment by everaldomatias** [comment]
Qual a dificuldade?

Pensei em algo assim:

```

if( get_option('cor_barra') ) {
    $css = get_option('cor_barra');
} else {
    $css = #666666 /* default */;
}

```

E nas div's coloca como style mesmo. Você acha isso ruim?

**Comment by matheusgimenez** [comment]
Esse é o problema.. não é meio pesado ir setando div por div?

Pensei no seguinte pra resolver de vez, criar uma classe pra todos elementos com a cor modificada e no footer jogar uma tag style e setar lá

**Comment by everaldomatias** [comment]
Perfeito também!!!
Manda Brasa!
